// flow-typed signature: c379be72d9fffb7289c948a84b41c8ba
// flow-typed version: <<STUB>>/react-native-image-placeholder_v1.0.14/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-image-placeholder'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-image-placeholder' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-image-placeholder/index' {
  declare module.exports: $Exports<'react-native-image-placeholder'>;
}
declare module 'react-native-image-placeholder/index.js' {
  declare module.exports: $Exports<'react-native-image-placeholder'>;
}
