// flow-typed signature: 4c9eb4cb6190d07de3bcff2857726cc2
// flow-typed version: <<STUB>>/customize-cra_v0.2.12/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'customize-cra'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'customize-cra' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'customize-cra/index' {
  declare module.exports: $Exports<'customize-cra'>;
}
declare module 'customize-cra/index.js' {
  declare module.exports: $Exports<'customize-cra'>;
}
